### ISSUE TITLE
can I query the GPU ids allocated for a job?

### ISSUE THREAD

**Issue by ShuyangCao** [justanhduc/task-spooler#10]
Thanks for developing the tool! Right now `ts -i` only returns the number of GPUs allocated and `ts -p` returns the pid of the main process. To know which GPUs the process and its child processes actually uses, I am using `pgrep` and crossing ref with `nvidia-smi`. Is there an easy way to do so?

**Comment by justanhduc** [comment]
Hi @ShuyangCao. Thanks for your interest. The feature you asked is already available in [this branch](https://github.com/justanhduc/task-spooler/tree/gpu-ids-buffer) (via `ts -i`. It would take a bit more time to merge into master but it is stable enough to be used now.

**Comment by ShuyangCao** [comment]
Thanks. Can I reinstall ts using this branch without killing the server?

**Comment by justanhduc** [comment]
Unfortunately it's impossible 🙁

**Comment by ShuyangCao** [comment]
Thanks @justanhduc. It works great! Just wondering, does this branch support 0 wait time? As the scheduler has recorded the GPU ids, I think it probably can avoid assign jobs to the same GPU, right?

**Comment by justanhduc** [comment]
Hi @ShuyangCao. Yes it does! Now the server will assign GPUs to client instead of letting client choose as before, so queued jobs are executed immediately if there are available slots and GPUs.
