### ISSUE TITLE
Make cpu_only a make/cmake toggle and drop the cpu_only branch ?

### ISSUE THREAD

**Issue by AdelKS** [justanhduc/task-spooler#16]
Hello!

To simplify packaging (I want to write an ebuild for Gentoo's GURU) so the code given in the releases tarballs can be used directly, it would be awesome if you could merge the `cpu_only` into master and make it into a `cmake` toggle for example, and/or maybe make the GPU queuing a toggle. Is it very difficult for you ? Another option is to add the `cpu_only` source code to the releases.

Thanks!

Adel

**Comment by justanhduc** [comment]
Hi @AdelKS. It's a good idea. The first option is what I have been longing for. However, I suppose it will require some restructuring of the codes, which currently I cannot find time for. The second option is can be a short-term solution, but doing so will lose all history of the `cpu-only` branch. Btw, there is a tar ball for the `cpu-only` branch in each release (for e.g., [here](https://github.com/justanhduc/task-spooler/releases/tag/v1.3.0-cpu). Is it not what you need?

**Comment by AdelKS** [comment]
Thanks for your answer! Good luck!

> Btw, t[here](https://github.com/justanhduc/task-spooler/releases/tag/v1.3.0-cpu) is a tar ball for the cpu-only branch in each release (for e.g., here. Is it not what you need?

I did not see it as I only checked the "Releases" page and not the tags, that one is good yes ! Thank you

**Comment by justanhduc** [comment]
Hey @AdelKS. Finally I could merge the two branches together! Please check out the latest master. Maybe it's not stable for now, but so far I haven't encountered any problem.

**Comment by AdelKS** [comment]
Hello @justanhduc, sorry for the late answer, I was busy with other projects ! :D 

Okay, I tried to compile master and unfortunately I cannot find a way to disable GPU support, and I get this error message:

```
CMake Error at /usr/share/cmake/Modules/CMakeDetermineCUDACompiler.cmake:180 (message):
  Failed to find nvcc.

  Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
  variable.
```

**Comment by justanhduc** [comment]
Hi @AdelKS. I will investigate it. But I think installing using `make` should work because it is the main method I use during development while `CMake` is a bit an afterthought. Please try installing via `make`.
