### ISSUE TITLE
Prompt to uninstall the apt installation of tsp before running ts in README

### ISSUE THREAD

**Issue by HAL-42** [justanhduc/task-spooler#21]
An error message 'Error calling recv_msg in c_check_version' occurs immediately when runing `ts`, `ts [action]`, etc when tsp server installed by apt is runing.
In README, It will be nice to prompt beginer uninstalling tsp or runing `tsp -K`  before using `ts`.
And thank you for this tool, it is very useful.

**Comment by justanhduc** [comment]
Hey @HAL-42. Thanks for using `ts` and the suggestion as well. I updated the readme per your suggestion. Let me know if there's anything else. Cheers!
