### ISSUE TITLE
Structured output

### ISSUE THREAD

**Issue by bstee615** [justanhduc/task-spooler#25]
Thank you for this awesome tool!

I made a web app to manage multiple task queues since in my own workflow I usually use 2-3 queues and would like notifications when the items are done https://github.com/bstee615/task-spooler-gui. I managed to parse the output of the 'tsp' command, but it is not very machine-readable. I need a structured output in order to parse the current status easily and precisely. I think adding an option -J to output JSON would be helpful.

I will have some time soon and will try to implement it in the coming weeks. Will you be open to a PR?

By the way, I just got through a busy period of 2 back-to-back deep learning paper submissions and would not have finished the experiments as easily without this friendly tool. Thank you.

**Comment by justanhduc** [comment]
Hey @bstee615. Thanks for your kind words! I'm so happy that you found it useful for your research. I hope your submissions will get through smoothly.
I ALWAYS welcome PR, so please go ahead with your initiative. I can only get so far with my time and ability, so any help to make `ts` useful is more than welcome!
I think GUI is a great idea, as once in a while I feel like I need it too. Btw, I can't access to your repo. Perhaps you still made it private? Do you mind sharing with me?

**Comment by bstee615** [comment]
Yes, it was private. I made it public. Ok, I'll try to prepare a PR :smile:
