### ISSUE TITLE
Please edit the README

### ISSUE THREAD

**Issue by m040601** [justanhduc/task-spooler#26]
First of all, thank you so much for your work and commitment to this old, so very usefull and so very underrated tool.

I ended up here accidentaly, by googling "task-spooler". I already know about the original repo by Luis and everything written there. I was looking for more updated information and what people are doing, and plan to to, nowadays, 2022 with this tool.

I then stumbled on your github repo. Very nice to know somebody has interest and is commited to working on this tool.

But, it took me a lot of  unneccessayr wasted time and a looooot of trouble understanding what your repo is about.

There is an explanation for that. 

You have an horrible README, greeting every one that lands the first time in your page. 

You seem to have copied the original README and started doing "little edits", crossing out somethings, addding little notes here and there.

You just put the "homepage" of the project as a link to a blog post from 2021. That's not very professional.

Please dont take this personally. But the end result is an horrible Frankenstein.
It makes it sooooo difficult to quickly understand,

- what is this Repo ? Is it a fork ?  Is it a mirror of the original one ?
- is it some guy taking over the old one and maintaining it
- besides being a fork, what are the main points ? is it bug correction ? or is it new features planned ?
- what are your future intentions ? is this for personal use ? do you plan to keep on with it in a year or so ?

All of the above would be solved, if you just had a smaller, simple, to the point README. Not copied or adapted from the original repo. 

My personal opinion would be that you should actually have choosen another name, for example "task-spooler-ng". The original repo is dead. And is not gonna update with your work here. You have every right to fork. And deserve every credit for you work here. Since you are independent, are not pulling any more updates from the original repo, you, are effectevely the "new" task-spooler.

And eventually, what if the Luis old repo wakes up from the dead ? And starts updating it again ? A big mess. Again, my personal opinnion, change the name of your repo. It makes the work of other people eventually packgaging it for a Linux distribution like Debian or Archlinux unnecessary complex.

Start with a simple sentence, "This is a fork of XYZ, link". Enough.

Then add a couple more sentences about what "you" are doing here. Not what the old repo "task-spooler" did. That is history. Freshmeat and Luis is history. Put it in a HISTORY file.

Keep the README small. Put other stuff in the right place. Use the good old ones CHANGELOG file, a TODO , or a NEWS file. Simple plain text files.

Get rid of the old files written by Luis "OBJECTIVE" , "PLANS" etc. They dont make sense here. Put them in an "HISTORY" or "ARCHIVE" folder. You dont have to in chains like in a prison following the structure of the old repo. 

Dont put that advanced or niche stuff with the cpu/only or planned features before the important stuff. Important stuff, for first time users, is, "what is the point of task-spoooler", and  "how to quick start".

What is this (justanhduc) repo doing different from Luis repo is advanced or historic stuff.

Again, hope you take this as a constructive critic. The reason and my interest is  actually that I use Archlinux. We have a package for task-spooler using the old repo. With some patches. We saw your repo, and are considering a possible change, if the future looks good and stable. Just like the Debian package.

Thanks in advance.

**Comment by justanhduc** [comment]
Hello @m040601. Thanks for the criticism. I highly appreciate your time for drafting such a long comment, even though I would potentially appreciate much more if you left out all your personal frustration and somewhat overtone comments :). 
Please understand that I first started this fork entirely for my need. All the new features are totally guided by my friends and a few users' requests. Only until now, a few more people are aware of the app, which gives me a lot more motivation to make it better.
That said, definitely I am planning to improve the README, as not only you but also my friends have been constantly voicing discontent about it. Hopefully after having a more fancy one, `ts` will reach more users easily.
Again, thanks for all the comments, and I hope `ts` is stable enough for you to use in your project.

**Comment by justanhduc** [comment]
Fixed via c3e8232.
