### ISSUE TITLE
make cpu giving error: implicitly declaring library function 'snprintf' with type 'int 

### ISSUE THREAD

**Issue by jamesbraza** [justanhduc/task-spooler#29]
I just `git clone`'d the current master [bbfd33e](https://github.com/justanhduc/task-spooler/tree/bbfd33e4bc25f38a48e9e55bca86a0b07c51dcd0) and ran `make cpu`.  It outputs an error in `list.c`:

```none
list.c:22:9: error: implicitly declaring library function 'snprintf' with type 'int (char *, unsigned long, const char *, ...)' [-Werror,-Wimplicit-function-declaration]
        snprintf(newline, len - 4, "%s", line);
        ^
```

Can you fix this error message?  It blocks the install for me.

---

I am using GNU Make 3.81 on Mac M1 with macOS Monterey version 12.6.

**Comment by justanhduc** [comment]
Hey @jamesbraza. Thanks for using Task Spooler. It seems like your error is similar to [here](https://github.com/justanhduc/task-spooler/issues/4). Could you please try the solution there and let me know if it can solve your problem?

**Comment by jamesbraza** [comment]
Closing as a duplicate of https://github.com/justanhduc/task-spooler/issues/4
