### ISSUE TITLE
Real-time log with Task-spooler

### ISSUE THREAD

**Issue by davidnvq** [justanhduc/task-spooler#3]
Thank you a lot for such a great tool. I have been looking for this tool for a while.

In your [tutorial](https://librecv.github.io/blog/spooler/task%20manager/deep%20learning/2021/02/09/task-spooler.html), it said that: 
> To see the output, use the -c or -t flag. You should see the training in real-time. You can use ctrl+c to stop getting stdout anytime without actually canceling the experiment.

However, when I ran this command, `ts -c <id>`, it hang out for a while and returned the entire log once until the task finished.

When I checked the manual via `man ts`, I just see:

> -c [id ... It will block until all the output can be sent to standard output, and will exit with the job  errorlevel  as in -c.

Is there any way to work around this problem to view the stdout in real-time?

**Comment by justanhduc** [comment]
Hi @davidnvq. Thanks for your interest. Did you encounter this problem with the tutorial? My guess is that you print out to `stdout` but somehow it isn't flushed until the very end of the job. `ts` doesn't hang. It just doesn't have anything to show until the end of the job. Could you please try flushing immediately after printing something? (for e.g., if you use python 3 just throw `flush=True` to the `print` function, or better using `logging`). Let me know if it works.

**Comment by davidnvq** [comment]
Thank you a lot for your quick reply.
Indeed as you said, the following `print` doesn't work:
```
for i in range(100):
    time.sleep(0.1)
    print(i)
```
I haven't understood the mechanism why it doesn't work yet.
As your suggestion, adding `flush=True` or using `logging` both work for me.

**Comment by davidnvq** [comment]
Following your tutorial; It works perfectly. 
May you shed some light on why such `print` lines in `mnist.py` work?
```python
            print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                epoch, batch_idx * len(data), len(train_loader.dataset),
                100. * batch_idx / len(train_loader), loss.item()))
            .....
            print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
                    test_loss, correct, len(test_loader.dataset),
                    100. * correct / len(test_loader.dataset)))
 ```
But my following `print` doesn't work?
```python
import time

for i in range(100):
    time.sleep(0.1)    
    print(i) 
```
Both don't need to add `flush=True` to `print` function.

It would be much helpful if you can elaborate more on this problem.
If it bothers you, feel free to close the issue.
Many thanks.

**Comment by justanhduc** [comment]
Well, it is because in terminal, flush is triggered by `\n`, which is the default ending of `print`, but in other cases, like in this case the output is written to a file, it is not, and hence we need to call it manually. Please see [here](https://www.gnu.org/software/libc/manual/html_node/Buffering-Concepts.html) for more details. In short, `print` does not behave nicely with `ts`. I will close this for now. Feel free to reopen if you got any problem later.

**Comment by justanhduc** [comment]
@davidnvq I realized I didn't really answer your question. I am not sure either! I got a lot of unhappy experiences with `print` too. The solution is either flush after print or use `logging` which is more preffered.

**Comment by davidnvq** [comment]
Never mind about it. I'm indeed addicted to `task-spooler` now. If you can find a better way to resolve it, please kindly leave a message here.

**Comment by justanhduc** [comment]
Thanks. Feel free to contribute if you got any idea too :)
