### ISSUE TITLE
Unable to redirect output from command line

### ISSUE THREAD

**Issue by gauthier12** [justanhduc/task-spooler#48]
Hello.
I would like to redirect the output of my command launched by task-spooler.
I've seen comments using stdout redirection of the job but I haven't been able to use it.
I use ```ts "./test.sh > test.log``` but the output is still stored in a temporary file in ```/tmp```.
I've tried with a absolute path and with the ```tee``` command and still nothing.
The ```-o file``` option still output with a random suffix in /tmp.
The only way I've found is to create a temporary script and redirect the output from inside the script.
Is there something I am missing ?
Cheers

**Comment by justanhduc** [comment]
Hey @gauthier12. Sorry for the late reply. The way I see it, you need `--set_logdir` first and then use `-O` for the output file. Or am I missing something?

**Comment by gauthier12** [comment]
Hi, 
thanks for the response. The `-O` option still add a random name on the file and the --set_logdir change the server environnement so I'm not sure but the `--set_logdir` option can change the output directory of previously queued job still pending.
I've got a workaround by patching execute.c to output in the current directory and without the random part but I would prefer to work with the common redirection in the command line ( ```ts "./test.sh > test.log"``` ), it would be simpler for my users.

**Comment by ChristianS99** [comment]
redirecting output with ">" is a shell feature, and tsp is not a shell. So I guess it would require significant work to implement this.
What you can do, is launch a shell as your job:
```ts bash -c "echo abc > test.log"```
the argument after -c gets executed as inside bash, and therefore the output of the echo is redirected to the logfile.
Alternatively, put everything in a shell script and launch the script with ts

**Comment by gauthier12** [comment]
Thanks for your response. 
I am closing the issue. As I explained in my previous message, I ended patching task-spooler to output the stdout in the current folder and not in /tmp. This has more sense in a multi-user context to keep things separated.
