### ISSUE TITLE
How to send SIGINT to a process?

### ISSUE THREAD

**Issue by jasam-sheja** [justanhduc/task-spooler#57]
Is there a way to send SIGINT to one of the running processes, like using `ts -k [id]` to send SIGTERM?

**Comment by LeelaPrasadMaturu** [comment]
kill -SIGINT [PID]


find process id's with this command   ts -l

**Comment by jasam-sheja** [comment]
The `ts -l` command shows the job list but none of the columns show the PID!
Currently, I'm using `nvidia-smi` to pinpoint the PID, but it'd be nicer to do it from `ts`.

**Comment by CMGeldenhuys** [comment]
I believe you can get the PID using `ts -p`

**Comment by jasam-sheja** [comment]
Thanks. This is new! Now I can call `kill -s SIGINT $(ts -p [id])`

**Comment by jasam-sheja** [comment]
Closing ...
