### ISSUE TITLE
Would it be possible to allow cpu jobs to run independently from gpu jobs?

### ISSUE THREAD

**Issue by camattelaer** [justanhduc/task-spooler#60]
Hi 

To give an example: i have 4 gpus, so i typically set `ts -S 4` to run 4 jobs at the same time. `ts` handles this beautifully and distributes the work over the 4 gpus. However, i also run jobs on cpu with `ts -G 0` and this will keep allocating until one job finishes and opens up a space in the queue although it could run since it does not have to run on a gpu. In the ideal case, you could set a variable with the amount of cores/threads required an fill your cpu as well. 

If this is beyond the scope of the project, no problem. Just wanted to ask.

Kind regards
Charles-Alexandre

**Comment by CMGeldenhuys** [comment]
We ran into a similar issue. A workaround was to create as many slots as there are CPU cores. Then jobs use the `-N` argument to specify the number of slots (i.e. cores) a job would like to use and `-G` for the number of GPUs. That said, there is nothing that actually will enforce the resource allocation (in the case of CPU usage), it has to be handled by the user script.

**Comment by camattelaer** [comment]
oh okay, that seems to be sufficient for me currently.

Only recently switched from vanilla task-spooler to this repo and it has been amazing. Vanilla doesn't have the `-N` flag and i overlooked! Ty for the help!

Will close as workaround is available

CA
