### ISSUE TITLE
Can I limit the distributed GPUs?

### ISSUE THREAD

**Issue by bermeitinger-b** [justanhduc/task-spooler#8]
I'm using your script on a machine with 16 GPUs. For my tasks, I want specific GPUs to not be used or rather select which GPUs are used.

For example, I want GPUs 0-8 to be available to `ts` but 9-15 be left alone. Is this something that can be done?

**Comment by justanhduc** [comment]
Hi @bermeitinger-b. You can pull to get the new features. To run multiple processes in a GPU, you can set the free memory threshold (in percentage) appropriately via `ts --set_gpu_free_perc`.
